{
 "title": "FlaskAppDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "by_endpoint_counter_total{endpoint=\"home\", instance=\"flask-app:5000\", job=\"flask-app\", method=\"GET\", path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests by min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(by_endpoint_counter_total{job=\"flask-app\",instance=\"flask-app:5000\",endpoint=\"home\"}[1m]))*60",
     "legendFormat": "Home"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqs/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(by_endpoint_counter_total{job=\"flask-app\",instance=\"flask-app:5000\",endpoint=\"home\"}[1m]))*60",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node-explorer\",instance=\"node-exporter:9100\",mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-explorer\",instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-explorer\",instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-explorer\",instance=\"node-exporter:9100\",device!~\"tmpfs | nsfs\", device!=\"gvfsd-fuse\", device!~\"/def/loop.\"} - node_filesystem_avail_bytes{job=\"node-explorer\",instance=\"node-exporter:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node-explorer\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node-explorer\",instance=\"node-exporter:9100\",device!~\"tmpfs | nsfs\", device!=\"gvfsd-fuse\", device!~\"/def/loop.\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}